#!/usr/bin/env bash

# Assemble a deployable SCAN-Planner runtime from an S100 colcon install tree.
# Run inside the official TROS cross-compilation container so every resolved
# dependency is an ARM64 target library rather than a host library.

set -euo pipefail

if [[ $# -ne 3 ]]; then
  echo "usage: $0 <install-root> <sysroot> <output-root>" >&2
  exit 2
fi

install_root=$(realpath "$1")
sysroot=$(realpath "$2")
output_root=$(realpath -m "$3")

if [[ ! -d "${install_root}/lib" || ! -d "${install_root}/share" ]]; then
  echo "ERROR: invalid colcon install tree: ${install_root}" >&2
  exit 1
fi
if [[ ! -d "${sysroot}/usr" ]]; then
  echo "ERROR: invalid S100 sysroot: ${sysroot}" >&2
  exit 1
fi
case "${output_root}" in
  /|/data|/home|/opt|/tmp|/usr|"${install_root}"|"${sysroot}")
    echo "ERROR: unsafe runtime output path: ${output_root}" >&2
    exit 1
    ;;
esac
case "${install_root}/" in
  "${output_root}/"*)
    echo "ERROR: runtime output cannot contain the install tree: ${output_root}" >&2
    exit 1
    ;;
esac
case "${output_root}/" in
  "${install_root}/"*)
    echo "ERROR: runtime output cannot be inside the install tree: ${output_root}" >&2
    exit 1
    ;;
esac
case "${sysroot}/" in
  "${output_root}/"*)
    echo "ERROR: runtime output cannot contain the sysroot: ${output_root}" >&2
    exit 1
    ;;
esac
case "${output_root}/" in
  "${sysroot}/"*)
    echo "ERROR: runtime output cannot be inside the sysroot: ${output_root}" >&2
    exit 1
    ;;
esac

rm -rf "${output_root}"
mkdir -p \
  "${output_root}/bin" \
  "${output_root}/config" \
  "${output_root}/lib" \
  "${output_root}/local" \
  "${output_root}/share"
: > "${output_root}/COLCON_IGNORE"

# Keep the generated C/C++ interface libraries and application executables.
# Static algorithm archives are build artifacts, not runtime dependencies, and
# are removed after the copy. Application executables remain under
# lib/<package>; bin contains stable product entry points only.
cp -a "${install_root}/lib/." "${output_root}/lib/"
find "${output_root}/lib" -maxdepth 1 -type f -name '*.a' -delete

# The S100 merged install keeps generated Python interfaces below local/. They
# are needed by ros2 topic/action CLI tools even though the planner is C++.
if [[ -d "${install_root}/local" ]]; then
  cp -a "${install_root}/local/." "${output_root}/local/"
fi

runtime_packages=(
  omni_robot_interfaces
  scan_planner_msgs
  plan_env
  path_searching
  bspline_opt
  traj_utils
  scan_planner
)

for package_name in "${runtime_packages[@]}"; do
  package_share="${install_root}/share/${package_name}"
  test -f "${package_share}/package.xml"
  cp -a "${package_share}" "${output_root}/share/${package_name}"

  package_config="${install_root}/share/${package_name}/config"
  if [[ -d "${package_config}" ]]; then
    mkdir -p "${output_root}/config/${package_name}"
    cp -a "${package_config}/." "${output_root}/config/${package_name}/"
  fi
done

test -d "${install_root}/share/ament_index"
cp -a "${install_root}/share/ament_index" "${output_root}/share/ament_index"

# This is a runtime, not a development SDK. CMake exports, environment hooks
# and generated prefix scripts point back into the cross-build workspace and
# are invalid once headers/static archives have been removed.
for package_name in "${runtime_packages[@]}"; do
  rm -rf \
    "${output_root}/share/${package_name}/cmake" \
    "${output_root}/share/${package_name}/environment" \
    "${output_root}/share/${package_name}/hook"
  find "${output_root}/share/${package_name}" -maxdepth 1 -type f \
    \( -name 'local_setup.*' -o -name 'package.*' \) \
    ! -name 'package.xml' -delete
done
rm -rf \
  "${output_root}/share/ament_index/resource_index/parent_prefix_path"
find "${output_root}/share" -depth -type d -empty -delete

# Generated C sources and host-generated bytecode are not runtime inputs. Keep
# the Python modules and ARM64 extension modules used by ros2 topic/action.
find "${output_root}/local" -type f -name '*.c' -delete
find "${output_root}/local" -depth -type d -name '__pycache__' -exec rm -rf {} +

runtime_executables=(
  scan_planner_node
  closed_loop_controller
  global_path_publisher
)
for executable_name in "${runtime_executables[@]}"; do
  executable="${output_root}/lib/scan_planner/${executable_name}"
  test -x "${executable}"
  ln -sfn "../lib/scan_planner/${executable_name}" \
    "${output_root}/bin/${executable_name}"
done

# Product artifacts contain only the real-robot planner path. The shared
# run.launch.py remains because it supports real hardware, while resources that
# can only start excluded simulation binaries are intentionally pruned.
rm -f \
  "${output_root}/lib/scan_planner/keypoint_recorder.py" \
  "${output_root}/share/scan_planner/config/simulator.yaml" \
  "${output_root}/share/scan_planner/launch/default.rviz" \
  "${output_root}/share/scan_planner/launch/rviz.launch.py" \
  "${output_root}/share/scan_planner/launch/simulator.launch.py" \
  "${output_root}/config/scan_planner/simulator.yaml"
rm -rf \
  "${output_root}/share/scan_planner/launch/__pycache__" \
  "${output_root}/share/scan_planner/rviz"

while IFS= read -r -d '' packaged_executable; do
  case "$(basename "${packaged_executable}")" in
    scan_planner_node|closed_loop_controller|global_path_publisher)
      ;;
    *)
      echo "ERROR: executable is not in the S100 runtime allowlist: ${packaged_executable}" >&2
      exit 1
      ;;
  esac
done < <(find "${output_root}/lib/scan_planner" -maxdepth 1 \
  -type f -perm /111 -print0)

cat > "${output_root}/setup.bash" <<'SETUP'
#!/usr/bin/env bash

set -eo pipefail
_scan_planner_s100_root=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# The target board supplies the base OS, ROS CLI and RMW implementation. This
# archive supplies the application prefix and its recursively resolved ARM64
# shared-library dependencies.
set +u
if [[ -f /opt/tros/humble/setup.bash ]]; then
  # shellcheck disable=SC1091
  source /opt/tros/humble/setup.bash
elif [[ -f /opt/ros/humble/setup.bash ]]; then
  # shellcheck disable=SC1091
  source /opt/ros/humble/setup.bash
else
  echo "ERROR: ROS 2 Humble/TogetheROS is not installed" >&2
  return 1 2>/dev/null || exit 1
fi
set -u

export PATH="${_scan_planner_s100_root}/bin:${PATH}"
export LD_LIBRARY_PATH="${_scan_planner_s100_root}/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
export AMENT_PREFIX_PATH="${_scan_planner_s100_root}${AMENT_PREFIX_PATH:+:${AMENT_PREFIX_PATH}}"

for _scan_planner_python_dir in \
  "${_scan_planner_s100_root}/local/lib/python3.10/dist-packages" \
  "${_scan_planner_s100_root}/local/lib/python3.10/site-packages" \
  "${_scan_planner_s100_root}/lib/python3.10/dist-packages" \
  "${_scan_planner_s100_root}/lib/python3.10/site-packages"; do
  if [[ -d "${_scan_planner_python_dir}" ]]; then
    export PYTHONPATH="${_scan_planner_python_dir}${PYTHONPATH:+:${PYTHONPATH}}"
  fi
done

unset _scan_planner_python_dir _scan_planner_s100_root
SETUP
chmod 755 "${output_root}/setup.bash"

cat > "${output_root}/bin/run_product_planner.sh" <<'RUNNER'
#!/usr/bin/env bash

set -euo pipefail
_scan_planner_product_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
# shellcheck disable=SC1091
source "${_scan_planner_product_root}/setup.bash"

# Product safety invariants are deliberately appended after caller overrides.
# This package has no simulation nodes and must wait for omni_tf_manager.
exec ros2 launch scan_planner run.launch.py \
  "$@" \
  is_real_world:=true \
  controller_mode:=closed_loop \
  require_tf_ready:=true \
  use_sim_time:=false \
  publish_robot_description:=false \
  enable_deprecated_zsibot_transport:=false \
  use_zsibot_bridge:=false \
  use_zsibot_udp_client:=false
RUNNER
chmod 755 "${output_root}/bin/run_product_planner.sh"

cat > "${output_root}/README.txt" <<'README'
SCAN-Planner for RDK S100

1. Copy or extract this directory on the S100.
2. Start the production planner:
   ./bin/run_product_planner.sh
3. Append launch overrides when required, for example:
   ./bin/run_product_planner.sh sensor_type:=lidar navi_mode:=1

The bundle contains the production planner packages, launch/config resources,
generated interface support and recursively resolved ARM64 shared libraries.
It deliberately excludes simulator packages, Go2 assets, the deprecated
open-loop controller and the vendor transport bridge.

run_product_planner.sh enforces the real-robot, closed-loop path, waits for
/omni/tf_manager/ready and prevents this artifact from owning a vendor SDK.

The board must provide RDK OS and ROS 2 Humble/TogetheROS under
/opt/tros/humble or /opt/ros/humble. See lib/DEPENDENCIES.txt for libraries
copied from the pinned target ROS/sysroot during packaging.
README

# Never shadow the target board's loader or glibc. Other DT_NEEDED libraries
# are bundled to make the application runtime independent of development-only
# packages that happened to exist in the cross-compilation container.
is_system_library() {
  case "$1" in
    ld-linux-aarch64.so.1|libanl.so.*|libc.so.*|libdl.so.*|libm.so.*|\
      libnsl.so.*|libpthread.so.*|libresolv.so.*|librt.so.*|libutil.so.*)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

search_roots=(
  /opt/ros/humble/lib
  /opt/ros/humble/lib/aarch64-linux-gnu
  "${sysroot}/usr/lib/aarch64-linux-gnu"
  "${sysroot}/usr/lib"
  "${sysroot}/lib/aarch64-linux-gnu"
  /usr/aarch64-linux-gnu/lib
)

resolve_library() {
  local library_name=$1
  local search_root
  local candidate

  for search_root in "${search_roots[@]}"; do
    [[ -d "${search_root}" ]] || continue
    candidate=$(find -L "${search_root}" -maxdepth 2 -type f \
      -name "${library_name}" -print -quit 2>/dev/null || true)
    if [[ -n "${candidate}" ]]; then
      printf '%s\n' "${candidate}"
      return 0
    fi
  done
  return 1
}

declare -a elf_queue=()
declare -A queued=()
declare -A processed=()

while IFS= read -r -d '' candidate; do
  if file "${candidate}" | grep -q 'ELF'; then
    elf_queue+=("${candidate}")
    queued["${candidate}"]=1
  fi
done < <(find "${output_root}/lib" "${output_root}/local" -type f -print0 2>/dev/null)

dependency_manifest="${output_root}/lib/DEPENDENCIES.txt"
: > "${dependency_manifest}"

queue_index=0
while (( queue_index < ${#elf_queue[@]} )); do
  elf_file=${elf_queue[queue_index]}
  queue_index=$((queue_index + 1))

  [[ -z "${processed[${elf_file}]:-}" ]] || continue
  processed["${elf_file}"]=1

  while IFS= read -r library_name; do
    [[ -n "${library_name}" ]] || continue
    if is_system_library "${library_name}"; then
      continue
    fi

    bundled_library="${output_root}/lib/${library_name}"
    if [[ ! -f "${bundled_library}" ]]; then
      if ! source_library=$(resolve_library "${library_name}"); then
        echo "ERROR: cannot resolve ARM64 runtime dependency ${library_name}" \
          "required by ${elf_file}" >&2
        exit 1
      fi
      cp -L "${source_library}" "${bundled_library}"
      chmod 755 "${bundled_library}"
      printf '%s <- %s\n' "${library_name}" "${source_library}" \
        >> "${dependency_manifest}"
    fi

    if [[ -z "${queued[${bundled_library}]:-}" ]]; then
      elf_queue+=("${bundled_library}")
      queued["${bundled_library}"]=1
    fi
  done < <(
    readelf -d "${elf_file}" 2>/dev/null \
      | sed -n 's/.*Shared library: \[\([^]]*\)\].*/\1/p'
  )
done

sort -u -o "${dependency_manifest}" "${dependency_manifest}"

test -x "${output_root}/bin/scan_planner_node"
test -x "${output_root}/bin/closed_loop_controller"
test -x "${output_root}/bin/global_path_publisher"
test -x "${output_root}/bin/run_product_planner.sh"
test -f "${output_root}/config/scan_planner/planner.yaml"
test -f "${output_root}/share/scan_planner/launch/run.launch.py"
test -d "${output_root}/share/ament_index"
test -s "${dependency_manifest}"

for interface_package in omni_robot_interfaces scan_planner_msgs; do
  interface_python_elf=$(find \
    "${output_root}/local" "${output_root}/lib" \
    -type f \
    -path "*/python3.10/*-packages/${interface_package}/*.so" \
    -print -quit 2>/dev/null || true)
  if [[ -z "${interface_python_elf}" ]]; then
    echo "ERROR: missing Python typesupport ELF for ${interface_package}" >&2
    exit 1
  fi
done

elf_count=0
workspace_root=$(dirname "${install_root}")
while IFS= read -r -d '' bundled_file; do
  file_info=$(file "${bundled_file}")
  if grep -q 'ELF' <<<"${file_info}"; then
    if ! grep -Eq 'ARM aarch64|ARM64' <<<"${file_info}"; then
      echo "ERROR: non-ARM64 ELF in runtime bundle: ${file_info}" >&2
      exit 1
    fi
    if readelf -d "${bundled_file}" 2>/dev/null \
        | sed -n '/(RPATH)\|(RUNPATH)/p' \
        | grep -Fq "${workspace_root}"; then
      echo "ERROR: build-workspace RUNPATH in runtime ELF: ${bundled_file}" >&2
      readelf -d "${bundled_file}" 2>/dev/null \
        | sed -n '/(RPATH)\|(RUNPATH)/p' >&2
      exit 1
    fi
    elf_count=$((elf_count + 1))
  fi
done < <(find "${output_root}" -type f -print0)

metadata_leak=$(grep -RIlF "${workspace_root}" \
  "${output_root}" 2>/dev/null || true)
if [[ -n "${metadata_leak}" ]]; then
  echo "ERROR: cross-build path leaked into runtime metadata:" >&2
  printf '%s\n' "${metadata_leak}" >&2
  exit 1
fi

if (( elf_count == 0 )); then
  echo 'ERROR: runtime bundle contains no ARM64 ELF files' >&2
  exit 1
fi

echo "Runtime bundle: ${output_root}"
echo "ARM64 ELF files: ${elf_count}"
echo "Resolved dependencies: $(wc -l < "${dependency_manifest}")"
du -sh "${output_root}"
